#!/bin/bash
echo "[testing modules] with 2 threads"
./runtest.sh "./testQ 1" "open a queue then close it"
./runtest.sh "./testQ 2" "all functions with a NULL q"
./runtest.sh "./testQ 3" "get from an empty queue"
./runtest.sh "./testQ 4" "put then get 3 elements"
./runtest.sh "./testQ 5" "put NULL"
./runtest.sh "./testQ 6" "apply a function to an empty queue"
./runtest.sh "./testQ 7" "apply a function to an nonempty queue"
./runtest.sh "./testQ 8" "apply NULL to queue"
./runtest.sh "./testQ 9" "search an empty queue"
./runtest.sh "./testQ 10" "search a nonempty queue"
./runtest.sh "./testQ 11" "remove from an empty queue"
./runtest.sh "./testQ 12" "remove a queue with NULL"
./runtest.sh "./testQ 13" "search for something thats not in the queue"
./runtest.sh "./testQ 14" "remove an element that is not present in a queue"
./runtest.sh "./testH 1" "open a hash then close it"
./runtest.sh "./testH 2" "all functions with a NULL h"
./runtest.sh "./testH 3" "put 3 elements"
./runtest.sh "./testH 4" "search in hash"
./runtest.sh "./testH 5" "search for something that's not in hash"
./runtest.sh "./testH 6" "remove from hash"
./runtest.sh "./testH 7" "remove something that's not in hash"
./runtest.sh "./testH 8" "hash apply"
echo "[done]"

